---
- hosts: all
  tasks:
    - name: yum update
      become: yes
      yum:
        name: '*'
        state: latest

    - name: install development tools
      become: yes
      yum:
        name: '@Development tools'
        state: present

    - name: install software collections
      become: yes
      yum:
        name: centos-release-scl
        state: present

    - name: enable repository of software collections
      become: yes
      command: yum-config-manager --enable rhel-server-rhscl-7-rpms
