---
- hosts: all
  tasks:
    - name: yum update
      become: yes
      yum:
        name: '*'
        state: latest

    - name: install development tools
      become: yes
      yum:
        name: '@Development tools'
        state: present

    - name: install yum-utils
      become: yes
      yum:
        name: yum-utils
        state: present

    - name: install bash-completions
      become: yes
      yum:
        name: bash-completion

    - name: install zsh
      become: yes
      yum:
        name:
          - zsh

    - name: download repoInfo for zsh-completions
      become: yes
      get_url:
        url: "https://download.opensuse.org/repositories/shells:zsh-users:zsh-completions/CentOS_7/shells:zsh-users:zsh-completions.repo"
        dest: /tmp/shells:zsh-users:zsh-completions.repo

    - name: add repoInfo for zsh-completions
      become: yes
      command: cp shells:zsh-users:zsh-completions.repo /etc/yum.repos.d/
      args:
        chdir: /tmp

    - name: install zsh-completions
      become: yes
      yum:
        name:
          - zsh-completions

    - name: set zsh as default shell for vagrant user
      become: yes
      command: chsh -s '/usr/bin/zsh'

    - name: install tmux
      become: yes
      yum:
        name: tmux

    - name: install dotfiles
      shell: curl -L https://raw.githubusercontent.com/yajamon/dotfiles/master/install.sh | sh

    - name: install software collections
      become: yes
      yum:
        name: centos-release-scl
        state: present

    - name: enable repository of software collections
      become: yes
      command: yum-config-manager --enable rhel-server-rhscl-7-rpms

    - name: install python3.5 from SCL
      become: yes
      yum:
        name:
          - rh-python35-python
          - rh-python35-python-virtualenv

    - name: enable rh-python35
      become: yes
      shell: echo 'source /opt/rh/rh-python35/enable' > /etc/profile.d/rh-python35.sh

    - name: install Apache 2.4 from SCL
      become: yes
      yum:
        name:
          - httpd24-httpd
          - httpd24-mod_ssl
          - httpd24-mod_session
          - httpd24-mod_proxy_html

    - name: enable Apache 2.4
      become: yes
      shell: echo 'source /opt/rh/httpd24-httpd/enable' > /etc/profile.d/httpd24-httpd.sh

    - name: install gcc, gcc-c++ from devtoolset6
      become: yes
      yum:
        name:
          - devtoolset-6-gcc
          - devtoolset-6-binutils
          - devtoolset-6-gcc-c++
          - devtoolset-6-gcc-gfortran

    - name: enable devtoolset-6
      become: yes
      shell: echo 'source /opt/rh/devtoolset-6/enable' > /etc/profile.d/devtoolset-6.sh

    - name: download peco
      get_url:
        url: https://github.com/peco/peco/releases/download/v0.5.1/peco_linux_amd64.tar.gz
        dest: /tmp/peco_linux_amd64.tar.gz

    - name: unarchive peco
      unarchive:
        remote_src: yes
        src: /tmp/peco_linux_amd64.tar.gz
        dest: /tmp/

    - name: install peco
      become: yes
      command: cp peco_linux_amd64/peco /usr/local/bin/
      args:
        chdir: /tmp
