---
- hosts: all
  tasks:
    - name: yum update
      become: yes
      yum:
        name: '*'
        state: latest

    - name: install development tools
      become: yes
      yum:
        name: '@Development tools'
        state: present

    - name: install yum-utils
      become: yes
      yum:
        name: yum-utils
        state: present

    - name: install software collections
      become: yes
      yum:
        name: centos-release-scl
        state: present

    - name: enable repository of software collections
      become: yes
      command: yum-config-manager --enable rhel-server-rhscl-7-rpms

    - name: install python3.5 from SCL
      become: yes
      yum:
        name:
          - rh-python35
          - rh-python35-python-virtualenv

    - name: enable rh-python35
      become: yes
      shell: echo 'source /opt/rh/rh-python35/enable' > /etc/profile.d/rh-python35.sh
